# Generated by Django 3.1.3 on 2020-11-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20201121_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montyhole',
            name='created_at',
        ),
    ]
