# Generated by Django 3.1.3 on 2020-11-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
